#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

mgilet_notification:
  resource: "@MgiletNotificationBundle/Controller/"
  prefix: /notifications

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"